---

<center><h1> üìç üìç Aggregating and Summarizing DataFrames üìç üìç </h1></center>

---

- How to calculate sum, mean, median and mode of a column?
- How to get the summary of the numerical variables?
- How to get number of missing values in each columns?
- How to group the data based on categories of one column?
- How to group the data based on categories of multiple columns?
- How to create new feature using the aggregated results of a column?

---

#### `READ THE DATASET`

- In this notebook, we are going to use the big mart sales data that we have used previously. It is stored in the folder name `datasets`.

In [1]:
# import the pandas library
import pandas as pd

In [3]:
# read the big mart sales data
data = pd.read_csv('datasets/big_mart_sales.csv')

In [4]:
# view the top rows of the data
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

---

#### `How to calculate sum, mean, median and mode of a column?`

---

In [5]:
# calculate the sum of all MRP
data.Item_MRP.sum()

1201681.4808

In [6]:
# calculate the average Item_MRP
data.Item_MRP.mean()

140.9927819781767

In [7]:
# calculate the median of Item_MRP
data.Item_MRP.median()

143.0128

In [8]:
# find out the most frequent outlet type
data.Outlet_Type.mode()

0    Supermarket Type1
dtype: object

In [9]:
data.Outlet_Type.value_counts()

Supermarket Type1    5577
Grocery Store        1083
Supermarket Type3     935
Supermarket Type2     928
Name: Outlet_Type, dtype: int64

---

#### `How to get the summary of the numerical variables?`

To get the summary of the numerical variables we have describe function in pandas.

---

In [10]:
# get the summary
data.describe()

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales
count,7060.000000,8523.000000,8523.000000,8523.000000,8523.000000
mean,12.857645,0.066132,140.992782,1997.831867,2181.288914
std,4.643456,0.051598,62.275067,8.371760,1706.499616
min,4.555000,0.000000,31.290000,1985.000000,33.290000
25%,8.773750,0.026989,93.826500,1987.000000,834.247400
50%,12.600000,0.053931,143.012800,1999.000000,1794.331000
75%,16.850000,0.094585,185.643700,2004.000000,3101.296400
max,21.350000,0.328391,266.888400,2009.000000,13086.964800

---

#### `How to get number of missing values in each columns?`

---

In [11]:
data.isna().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

----
#### `How to group the data based on categories of one column?`
---

#### `GROUP BY`


- Calculate the average MRP of each `Item_Type` using groupby.

---

In [12]:
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [13]:
d = data.groupby(['Item_Type'])
d

In [14]:
d.first()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
Item_Type,,,,,,,,,,,
Baking Goods,FDP36,10.395,Regular,0.000000,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
Breads,FDO23,17.850,Low Fat,0.000000,93.1436,OUT045,2002,Medium,Tier 2,Supermarket Type1,2174.5028
Breakfast,FDP49,9.000,Regular,0.069089,56.3614,OUT046,1997,Small,Tier 1,Supermarket Type1,1547.3192
Canned,FDC14,21.350,Regular,0.072222,43.6454,OUT019,1985,Small,Tier 1,Grocery Store,125.8362
Dairy,FDA15,9.300,Low Fat,0.016047,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
Frozen Foods,FDH17,16.200,Regular,0.016687,96.9726,OUT045,2002,Small,Tier 2,Supermarket Type1,1076.5986
Fruits and Vegetables,FDX07,19.200,Regular,0.000000,182.0950,OUT010,1998,Medium,Tier 3,Grocery Store,732.3800
Hard Drinks,DRI11,11.650,Low Fat,0.034238,113.2834,OUT027,1985,Medium,Tier 3,Supermarket Type3,2303.6680
Health and Hygiene,NCB42,11.800,Low Fat,0.008596,115.3492,OUT018,2009,Medium,Tier 3,Supermarket Type2,1621.8888
Household,NCD19,8.930,Low Fat,0.000000,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
Meat,FDN15,17.500,Low Fat,0.016760,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
Others,NCN07,18.500,Low Fat,0.056816,132.1284,OUT010,1998,Small,Tier 3,Grocery Store,263.6568
Seafood,FDG33,10.395,Regular,0.139561,170.4764,OUT027,1985,Medium,Tier 3,Supermarket Type3,3435.5280
Snack Foods,FDO10,13.650,Regular,0.012741,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528
Soft Drinks,DRC01,5.920,Regular,0.019278,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
Starchy Foods,FDH35,18.250,Low Fat,0.000000,164.7526,OUT045,2002,Medium,Tier 2,Supermarket Type1,4604.6728

#### `GROUPBY MEAN`

---

In [15]:
d.mean()

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales
Item_Type,,,,,
Baking Goods,12.277108,0.069169,126.380766,1997.728395,1952.971207
Breads,11.346936,0.066255,140.952669,1997.657371,2204.132226
Breakfast,12.768202,0.085723,141.788151,1997.336364,2111.808651
Canned,12.305705,0.068129,139.763832,1998.152542,2225.194904
Dairy,13.426069,0.072427,148.499208,1997.681818,2232.542597
Frozen Foods,12.867061,0.065645,138.503366,1998.024533,2132.867744
Fruits and Vegetables,13.224769,0.068513,144.581235,1997.719968,2289.009592
Hard Drinks,11.400328,0.064943,137.077928,1998.177570,2139.221622
Health and Hygiene,13.142314,0.055216,130.818921,1997.734615,2010.000265
Household,13.384736,0.061322,149.424753,1997.784615,2258.784300
Meat,12.817344,0.062284,139.882032,1997.341176,2158.977911
Others,13.853285,0.060241,132.851430,1997.662722,1926.139702
Seafood,12.552843,0.074976,141.841719,1997.734375,2326.065928
Snack Foods,12.987880,0.066850,146.194934,1997.886667,2277.321739
Soft Drinks,11.847460,0.063972,131.492506,1998.098876,2006.511735
Starchy Foods,13.690731,0.067564,147.838023,1998.581081,2374.332773

In [16]:
d.mean()['Item_MRP']

Item_Type
Baking Goods             126.380766
Breads                   140.952669
Breakfast                141.788151
Canned                   139.763832
Dairy                    148.499208
Frozen Foods             138.503366
Fruits and Vegetables    144.581235
Hard Drinks              137.077928
Health and Hygiene       130.818921
Household                149.424753
Meat                     139.882032
Others                   132.851430
Seafood                  141.841719
Snack Foods              146.194934
Soft Drinks              131.492506
Starchy Foods            147.838023
Name: Item_MRP, dtype: float64

#### `GROUPBY MAX`

---

In [17]:
d.max()

<ipython-input-17-40fd91dbbcd8>:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  d.max()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
Item_Type,,,,,,,,,,
Baking Goods,FDZ60,20.85,reg,0.311090,265.5568,OUT049,2009,Tier 3,Supermarket Type3,7931.6754
Breads,FDZ35,20.85,reg,0.281510,263.6594,OUT049,2009,Tier 3,Supermarket Type3,8958.3390
Breakfast,FDR37,21.10,reg,0.274592,234.9300,OUT049,2009,Tier 3,Supermarket Type3,8209.3140
Canned,FDZ49,21.35,reg,0.328391,266.8884,OUT049,2009,Tier 3,Supermarket Type3,10306.5840
Dairy,FDZ50,20.70,reg,0.304737,266.6884,OUT049,2009,Tier 3,Supermarket Type3,10256.6490
Frozen Foods,FDZ52,20.85,reg,0.294939,264.8910,OUT049,2009,Tier 3,Supermarket Type3,9678.0688
Fruits and Vegetables,FDZ56,21.35,reg,0.321115,264.2252,OUT049,2009,Tier 3,Supermarket Type3,12117.5600
Hard Drinks,DRQ35,19.70,low fat,0.298205,261.4278,OUT049,2009,Tier 3,Supermarket Type3,7843.1240
Health and Hygiene,NCZ53,21.25,low fat,0.255348,266.6884,OUT049,2009,Tier 3,Supermarket Type3,9779.9362
Household,NCZ54,21.25,low fat,0.325781,264.7910,OUT049,2009,Tier 3,Supermarket Type3,13086.9648
Meat,FDZ51,21.25,reg,0.287017,261.5936,OUT049,2009,Tier 3,Supermarket Type3,9390.4432
Others,NCQ43,20.50,low fat,0.210596,254.9040,OUT049,2009,Tier 3,Supermarket Type3,6008.8450
Seafood,FDK45,20.75,low fat,0.256152,240.2880,OUT049,2009,Tier 3,Supermarket Type3,6503.5344
Snack Foods,FDZ58,21.25,reg,0.303743,264.9568,OUT049,2009,Tier 3,Supermarket Type3,10993.6896
Soft Drinks,DRZ24,20.75,reg,0.306543,263.5910,OUT049,2009,Tier 3,Supermarket Type3,9554.2300
Starchy Foods,FDZ34,21.20,reg,0.238366,263.0252,OUT049,2009,Tier 3,Supermarket Type3,8132.0812

---

#### `How to group the data based on categories of multiple columns?`


- Calculate the `average MRP` of each `Item_Type` for each category of `Outlet_Size`.


---

In [18]:
# step wise groupby

d = data.groupby(['Outlet_Size', 'Item_Type']).mean()
d

                                   Item_Weight  Item_Visibility    Item_MRP  \
Outlet_Size Item_Type
High        Baking Goods             12.036918         0.059490  129.202044
            Breads                   11.048000         0.065586  133.758960
            Breakfast                12.564231         0.075118  147.490585
            Canned                   11.922231         0.056733  135.442708
            Dairy                    13.071875         0.068907  153.509173
            Frozen Foods             13.250707         0.065639  136.829250
            Fruits and Vegetables    13.259613         0.061302  145.572870
            Hard Drinks              11.741957         0.062271  141.927522
            Health and Hygiene       13.028770         0.051031  135.110980
            Household                14.033398         0.053742  147.097522
            Meat                     13.384268         0.055831  137.244790
            Others                   14.008437         0.049660  132.576613
            Seafood                  13.002000         0.066497  134.864240
            Snack Foods              13.404560         0.059669  145.847086
            Soft Drinks              12.233776         0.053552  131.758473
            Starchy Foods            13.562632         0.073566  158.157074
Medium      Baking Goods             12.170112         0.060220  126.178568
            Breads                   11.679231         0.057480  140.861039
            Breakfast                11.668800         0.071658  134.537511
            Canned                   12.427517         0.063452  138.124851
            Dairy                    13.840695         0.063799  148.512174
            Frozen Foods             12.619946         0.059927  140.557015
            Fruits and Vegetables    13.212875         0.060720  142.971470
            Hard Drinks              11.160288         0.058881  142.837696
            Health and Hygiene       13.579727         0.048143  128.701865
            Household                13.683237         0.056420  147.711330
            Meat                     12.372527         0.064558  136.419132
            Others                   13.850811         0.057396  127.836181
            Seafood                  14.322500         0.081870  140.857619
            Snack Foods              12.908487         0.061292  148.779195
            Soft Drinks              11.679565         0.060093  128.269682
            Starchy Foods            14.289265         0.057441  148.419504
Small       Baking Goods             12.644236         0.073599  125.213364
            Breads                   10.792000         0.072865  145.523651
            Breakfast                13.930500         0.098983  130.568027
            Canned                   12.351060         0.071590  142.295429
            Dairy                    13.395503         0.081580  145.942101
            Frozen Foods             12.890000         0.069465  137.838544
            Fruits and Vegetables    13.144647         0.075157  148.313370
            Hard Drinks              11.646190         0.062429  129.758784
            Health and Hygiene       13.100330         0.059809  131.831535
            Household                13.388537         0.066570  153.965439
            Meat                     12.836839         0.062318  145.699250
            Others                   13.541316         0.058949  137.889211
            Seafood                  12.527500         0.085069  144.281760
            Snack Foods              12.859615         0.074044  144.351896
            Soft Drinks              11.906300         0.070324  132.855043
            Starchy Foods            13.245294         0.066771  150.270174

                                   Outlet_Establishment_Year  \
Outlet_Size Item_Type
High        Baking Goods                         1987.000000
            Breads                               1987.000000
            Breakfast                            1987.000000
            Canned                               1987.000000
            Dairy                                1987.000000
            Frozen Foods                         1987.000000
            Fruits and Vegetables                1987.000000
            Hard Drinks                          1987.000000
            Health and Hygiene                   1987.000000
            Household                            1987.000000
            Meat                                 1987.000000
            Others                               1987.000000
            Seafood                              1987.000000
            Snack Foods                          1987.000000
            Soft Drinks                          1987.000000
            Starchy Foods                        1987.000000
Medium      Baking Goods                         1997.591133
            Breads                               1997.024096
            Breakfast                            1998.055556
            Canned                               1997.949309
            Dairy                                1998.045872
            Frozen Foods                         1997.810219
            Fruits and Vegetables                1997.523002
            Hard Drinks                          1997.640000
            Health and Hygiene                   1997.470588
            Household                            1997.491349
            Meat                                 1996.825503
            Others                               1998.807692
            Seafood                              1997.666667
            Snack Foods                          1997.534314
            Soft Drinks                          1997.759124
            Starchy Foods                        1998.458333
Small       Baking Goods                         1996.786096
            Breads                               1997.154930
            Breakfast                            1995.333333
            Canned                               1997.513228
            Dairy                                1996.540404
            Frozen Foods                         1997.224900
            Fruits and Vegetables                1997.082317
            Hard Drinks                          1998.160000
            Health and Hygiene                   1996.926471
            Household                            1997.350195
            Meat                                 1996.302521
            Others                               1995.327273
            Seafood                              1996.200000
            Snack Foods                          1997.238806
            Soft Drinks                          1997.412698
            Starchy Foods                        1999.236842

                                   Item_Outlet_Sales
Outlet_Size Item_Type
High        Baking Goods                 2050.901134
            Breads                       2080.731528
            Breakfast                    2104.286508
            Canned                       2211.265203
            Dairy                        2453.181713
            Frozen Foods                 2214.096189
            Fruits and Vegetables        2405.118103
            Hard Drinks                  2363.590000
            Health and Hygiene           1953.042439
            Household                    2408.217992
            Meat                         2321.953141
            Others                       2202.383175
            Seafood                      1629.345760
            Snack Foods                  2473.968987
            Soft Drinks                  2351.727890
            Starchy Foods                2302.791947
Medium      Baking Goods                 2386.702771
            Breads                       2718.244814
            Breakfast                    2865.085356
            Canned                       2562.075105
            Dairy                        2725.360676
            Frozen Foods                 2612.229851
            Fruits and Vegetables        2844.100923
            Hard Drinks                  2551.079280
            Health and Hygiene           2475.142832
            Household                    2869.842203
            Meat                         2792.575217
            Others                       2410.746565
            Seafood                      2514.441257
            Snack Foods                  2799.134167
            Soft Drinks                  2437.250807
            Starchy Foods                2589.615229
Small       Baking Goods                 1724.681911
            Breads                       2158.795546
            Breakfast                    1715.988533
            Canned                       2038.457667
            Dairy                        1900.495836
            Frozen Foods                 1895.489818
            Fruits and Vegetables        1931.258454
            Hard Drinks                  1926.518932
            Health and Hygiene           1929.155500
            Household                    1974.824976
            Meat                         1800.519024
            Others                       1529.282073
            Seafood                      2550.513350
            Snack Foods                  1958.330459
            Soft Drinks                  1602.612305
            Starchy Foods                2588.753047

In [19]:
d['Item_MRP']

Outlet_Size  Item_Type
High         Baking Goods             129.202044
             Breads                   133.758960
             Breakfast                147.490585
             Canned                   135.442708
             Dairy                    153.509173
             Frozen Foods             136.829250
             Fruits and Vegetables    145.572870
             Hard Drinks              141.927522
             Health and Hygiene       135.110980
             Household                147.097522
             Meat                     137.244790
             Others                   132.576613
             Seafood                  134.864240
             Snack Foods              145.847086
             Soft Drinks              131.758473
             Starchy Foods            158.157074
Medium       Baking Goods             126.178568
             Breads                   140.861039
             Breakfast                134.537511
             Canned                   138.124851
             Dairy                    148.512174
             Frozen Foods             140.557015
             Fruits and Vegetables    142.971470
             Hard Drinks              142.837696
             Health and Hygiene       128.701865
             Household                147.711330
             Meat                     136.419132
             Others                   127.836181
             Seafood                  140.857619
             Snack Foods              148.779195
             Soft Drinks              128.269682
             Starchy Foods            148.419504
Small        Baking Goods             125.213364
             Breads                   145.523651
             Breakfast                130.568027
             Canned                   142.295429
             Dairy                    145.942101
             Frozen Foods             137.838544
             Fruits and Vegetables    148.313370
             Hard Drinks              129.758784
             Health and Hygiene       131.831535
             Household                153.965439
             Meat                     145.699250
             Others                   137.889211
             Seafood                  144.281760
             Snack Foods              144.351896
             Soft Drinks              132.855043
             Starchy Foods            150.270174
Name: Item_MRP, dtype: float64

---

#### `We can also do this using the pivot table also`


- Learn more about the pivot table here: 
    - https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html
    - https://www.analyticsvidhya.com/blog/2020/03/pivot-table-pandas-python/

---
Calculate the average MRP of each `Item_Type` using pivot table.

---

In [20]:
pd.pivot_table(data, index='Item_Type', values="Item_MRP", aggfunc= 'mean')

                         Item_MRP
Item_Type
Baking Goods           126.380766
Breads                 140.952669
Breakfast              141.788151
Canned                 139.763832
Dairy                  148.499208
Frozen Foods           138.503366
Fruits and Vegetables  144.581235
Hard Drinks            137.077928
Health and Hygiene     130.818921
Household              149.424753
Meat                   139.882032
Others                 132.851430
Seafood                141.841719
Snack Foods            146.194934
Soft Drinks            131.492506
Starchy Foods          147.838023

---

- Calculate the `average MRP` of each `Item_Type` for each category of `Outlet_Size` using pivot table

---

In [21]:
pd.pivot_table(data, index= ['Outlet_Size', 'Item_Type'], values= 'Item_MRP', aggfunc= 'mean')

                                     Item_MRP
Outlet_Size Item_Type
High        Baking Goods           129.202044
            Breads                 133.758960
            Breakfast              147.490585
            Canned                 135.442708
            Dairy                  153.509173
            Frozen Foods           136.829250
            Fruits and Vegetables  145.572870
            Hard Drinks            141.927522
            Health and Hygiene     135.110980
            Household              147.097522
            Meat                   137.244790
            Others                 132.576613
            Seafood                134.864240
            Snack Foods            145.847086
            Soft Drinks            131.758473
            Starchy Foods          158.157074
Medium      Baking Goods           126.178568
            Breads                 140.861039
            Breakfast              134.537511
            Canned                 138.124851
            Dairy                  148.512174
            Frozen Foods           140.557015
            Fruits and Vegetables  142.971470
            Hard Drinks            142.837696
            Health and Hygiene     128.701865
            Household              147.711330
            Meat                   136.419132
            Others                 127.836181
            Seafood                140.857619
            Snack Foods            148.779195
            Soft Drinks            128.269682
            Starchy Foods          148.419504
Small       Baking Goods           125.213364
            Breads                 145.523651
            Breakfast              130.568027
            Canned                 142.295429
            Dairy                  145.942101
            Frozen Foods           137.838544
            Fruits and Vegetables  148.313370
            Hard Drinks            129.758784
            Health and Hygiene     131.831535
            Household              153.965439
            Meat                   145.699250
            Others                 137.889211
            Seafood                144.281760
            Snack Foods            144.351896
            Soft Drinks            132.855043
            Starchy Foods          150.270174

---

#### `CROSS TAB`


- The crosstab() function is used to compute a frequency table of two or more factors. 
- By default, it computes a frequency table of the factors unless an array of values or an aggregation function which is passed. 

- Learn more about crosstab here: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.crosstab.html


---

In [23]:
pd.crosstab(data['Outlet_Size'], data['Item_Type'])

Item_Type,Baking Goods,Breads,Breakfast,Canned,Dairy,Frozen Foods,Fruits and Vegetables,Hard Drinks,Health and Hygiene,Household,Meat,Others,Seafood,Snack Foods,Soft Drinks,Starchy Foods
Outlet_Size,,,,,,,,,,,,,,,,
High,73,25,13,65,80,92,142,23,61,103,41,16,5,125,49,19
Medium,203,83,36,217,218,274,413,75,170,289,149,52,21,408,137,48
Small,187,71,30,189,198,249,328,50,136,257,119,55,20,335,126,38

---

#### `How to create new feature using the aggregated results of a column?`

Let's create a dataframe which contains Item_Identifier and the average Item_Visibility using the groupby function. 

---

In [24]:
average_item_visibility = data.groupby(['Item_Identifier'])['Item_Visibility'].mean().reset_index()
average_item_visibility

     Item_Identifier  Item_Visibility
0              DRA12         0.031956
1              DRA24         0.048062
2              DRA59         0.134718
3              DRB01         0.082126
4              DRB13         0.008002
...              ...              ...
1554           NCZ30         0.024956
1555           NCZ41         0.051623
1556           NCZ42         0.009044
1557           NCZ53         0.027775
1558           NCZ54         0.080426

[1559 rows x 2 columns]

---

#### Now, we want to create a new feature `average_item_visibility` using the above dataframe. 

Let's first define a function that will take the parameter `Item_Identifier` and return the corresponding average `Item_Visibilty` using the dataframe `average_item_visibility`

---

In [25]:
def get_item_visibility(x) :
    return average_item_visibility.loc[(average_item_visibility.Item_Identifier == x), 'Item_Visibility'].values[0]

In [26]:
# let's test it on the sample Item_Identifier
get_item_visibility('DRA24')

0.04806226414285714

---

Now, use the apply function to create the new feature. You just need to access the Item_Identifier column and use the apply method and pass the function that we have defined.

---

In [27]:
data['average_item_visibility'] = data.Item_Identifier.apply(get_item_visibility)

In [28]:
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,average_item_visibility
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,0.017387
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,0.019219
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,0.020145
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800,0.015274
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,0.008082

####  There is a better way of doing the above task is by using the transform function.

- The time taken by the transform function to perform the above operation is comparatively less over a large dataframe. That‚Äôs a sigificant advantage as comapred to the first approach we used.
- You can learn more about the transform function here: https://www.analyticsvidhya.com/blog/2020/03/understanding-transform-function-python/


---

In [29]:
data['average_item_visibility_2'] = data.groupby(['Item_Identifier'])['Item_Visibility'].transform('mean')

In [30]:
data[['average_item_visibility', 'average_item_visibility_2']]

      average_item_visibility  average_item_visibility_2
0                    0.017387                   0.017387
1                    0.019219                   0.019219
2                    0.020145                   0.020145
3                    0.015274                   0.015274
4                    0.008082                   0.008082
...                       ...                        ...
8518                 0.061705                   0.061705
8519                 0.046952                   0.046952
8520                 0.035203                   0.035203
8521                 0.120686                   0.120686
8522                 0.051565                   0.051565

[8523 rows x 2 columns]